// <auto-generated />
using System;
using Library_DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_EF.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Library_DB.Book", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasDiscriminator<string>("BookType").HasValue("Book");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Library_DB.BookDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BorrowedCopies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BookDetails");
                });

            modelBuilder.Entity("Library_DB.BookLoan", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BookId");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PersonId");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LibrarianId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReturnLibrarianId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("BookLoan");
                });

            modelBuilder.Entity("Library_DB.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Library_DB.Fantasy", b =>
                {
                    b.HasBaseType("Library_DB.Book");

                    b.HasDiscriminator().HasValue("Fantasy");
                });

            modelBuilder.Entity("Library_DB.Mystery", b =>
                {
                    b.HasBaseType("Library_DB.Book");

                    b.HasDiscriminator().HasValue("Mystery");
                });

            modelBuilder.Entity("Library_DB.NonFiction", b =>
                {
                    b.HasBaseType("Library_DB.Book");

                    b.HasDiscriminator().HasValue("NonFiction");
                });

            modelBuilder.Entity("Library_DB.Novel", b =>
                {
                    b.HasBaseType("Library_DB.Book");

                    b.HasDiscriminator().HasValue("Novel");
                });

            modelBuilder.Entity("Library_DB.SciFi", b =>
                {
                    b.HasBaseType("Library_DB.Book");

                    b.HasDiscriminator().HasValue("SciFi");
                });

            modelBuilder.Entity("Library_DB.Textbook", b =>
                {
                    b.HasBaseType("Library_DB.Book");

                    b.HasDiscriminator().HasValue("Textbook");
                });

            modelBuilder.Entity("Library_DB.Author", b =>
                {
                    b.HasBaseType("Library_DB.Person");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("Library_DB.Customer", b =>
                {
                    b.HasBaseType("Library_DB.Person");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("TEXT");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Library_DB.Librarian", b =>
                {
                    b.HasBaseType("Library_DB.Person");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Librarians", (string)null);
                });

            modelBuilder.Entity("Library_DB.Book", b =>
                {
                    b.HasOne("Library_DB.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library_DB.BookDetails", "BookDetails")
                        .WithOne()
                        .HasForeignKey("Library_DB.Book", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("BookDetails");
                });

            modelBuilder.Entity("Library_DB.BookLoan", b =>
                {
                    b.HasOne("Library_DB.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library_DB.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Library_DB.Author", b =>
                {
                    b.HasOne("Library_DB.Person", null)
                        .WithOne()
                        .HasForeignKey("Library_DB.Author", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Library_DB.Customer", b =>
                {
                    b.HasOne("Library_DB.Person", null)
                        .WithOne()
                        .HasForeignKey("Library_DB.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Library_DB.Librarian", b =>
                {
                    b.HasOne("Library_DB.Person", null)
                        .WithOne()
                        .HasForeignKey("Library_DB.Librarian", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
